#https://www.perplexity.ai/search/0638400d-59de-4d83-8e38-0cb807daf590

In [12]:
import numpy as np 
from numpy import ndarray
a:ndarray=np.arange(1000000)
l=list(range(1000000))
my_array:ndarray = np.arange(1000000)
my_list = list(range(1000000))


In [14]:
%time

for c in range(10) :
    l=[x*2 for x in l]

CPU times: total: 0 ns
Wall time: 0 ns


In [15]:
%time 

for _ in range(10):
    #list的comprehension,list綜合表達式
    my_lists = [x*2 for x in my_list]

CPU times: total: 0 ns
Wall time: 0 ns


In [18]:
%time for c in range(10):my_array2=a*2

CPU times: total: 31.2 ms
Wall time: 31.8 ms


In [16]:
%time for _ in range(10): my_array2 = my_array * 2

CPU times: total: 31.2 ms
Wall time: 38.2 ms


In [32]:
np.random.seed(1)
s=np.random.randint(50,101,(50,5))
print(s)

[[ 87  93  62  58  59]
 [ 61  55  65  50  66]
 [ 51  62  57  95  56]
 [ 75 100  70  87  68]
 [ 70  61  92  78  79]
 [ 64 100  54  73  73]
 [ 91  99  80  82  72]
 [ 63  91  59  57  72]
 [ 51  50  67  58  74]
 [ 63  97  92  58  80]
 [ 57  53  56  71  99]
 [ 53  54  74  99  93]
 [ 62  76  66  95  91]
 [ 68  65  50  54  75]
 [ 97  84  73  57  76]
 [ 75  90  72  59  53]
 [ 89  73  86  77  87]
 [ 69  88  58  82  84]
 [ 60  73  65  97  73]
 [ 75  57  78  60  96]
 [ 82  74  73  51  99]
 [ 63  53  50  63  56]
 [ 71  56  52  62  77]
 [ 71  61  57  63  58]
 [ 61  62  93  70  80]
 [ 86  89  57  95  54]
 [ 98  68  82  63  60]
 [ 73  67  57  74  60]
 [ 78  70  82  62  51]
 [ 80  91  74  68  83]
 [ 52  94  78  89  84]
 [ 60  82  91  68  72]
 [ 56  52  57  89  98]
 [ 65  55  67  92  70]
 [ 98  72  87  63  99]
 [100  83  70  60  82]
 [ 75  71  89  82  69]
 [ 75  99  64  63  70]
 [ 93  56  63  65  74]
 [ 59  52  57  55  86]
 [ 87  71  90  63  77]
 [ 99  99  97  63  90]
 [ 64  95  73  66  78]
 [ 92  95  

In [35]:
s.ndim
s.shape
s.size
s.dtype

dtype('int32')

In [34]:
s[1][4]

np.int32(66)

In [42]:
s[0] #shape(5,)
s[0,:] #shape(5,0)
s[0:1,:] #shape(1,5)

array([[87, 93, 62, 58, 59]], dtype=int32)

In [48]:
s[:2]
s[:2,:]
s[(0,1),:]

array([[87, 93, 62, 58, 59],
       [61, 55, 65, 50, 66]], dtype=int32)

In [45]:
s[(0,1,4),:]

array([[87, 93, 62, 58, 59],
       [61, 55, 65, 50, 66],
       [70, 61, 92, 78, 79]], dtype=int32)

In [49]:
s[:,:2]

array([[ 87,  93],
       [ 61,  55],
       [ 51,  62],
       [ 75, 100],
       [ 70,  61],
       [ 64, 100],
       [ 91,  99],
       [ 63,  91],
       [ 51,  50],
       [ 63,  97],
       [ 57,  53],
       [ 53,  54],
       [ 62,  76],
       [ 68,  65],
       [ 97,  84],
       [ 75,  90],
       [ 89,  73],
       [ 69,  88],
       [ 60,  73],
       [ 75,  57],
       [ 82,  74],
       [ 63,  53],
       [ 71,  56],
       [ 71,  61],
       [ 61,  62],
       [ 86,  89],
       [ 98,  68],
       [ 73,  67],
       [ 78,  70],
       [ 80,  91],
       [ 52,  94],
       [ 60,  82],
       [ 56,  52],
       [ 65,  55],
       [ 98,  72],
       [100,  83],
       [ 75,  71],
       [ 75,  99],
       [ 93,  56],
       [ 59,  52],
       [ 87,  71],
       [ 99,  99],
       [ 64,  95],
       [ 92,  95],
       [ 96,  50],
       [ 79,  83],
       [ 98,  82],
       [ 78,  80],
       [ 85,  82],
       [100,  65]], dtype=int32)

In [50]:
s[:30,-3:]

array([[62, 58, 59],
       [65, 50, 66],
       [57, 95, 56],
       [70, 87, 68],
       [92, 78, 79],
       [54, 73, 73],
       [80, 82, 72],
       [59, 57, 72],
       [67, 58, 74],
       [92, 58, 80],
       [56, 71, 99],
       [74, 99, 93],
       [66, 95, 91],
       [50, 54, 75],
       [73, 57, 76],
       [72, 59, 53],
       [86, 77, 87],
       [58, 82, 84],
       [65, 97, 73],
       [78, 60, 96],
       [73, 51, 99],
       [50, 63, 56],
       [52, 62, 77],
       [57, 63, 58],
       [93, 70, 80],
       [57, 95, 54],
       [82, 63, 60],
       [57, 74, 60],
       [82, 62, 51],
       [74, 68, 83]], dtype=int32)

ndarray的統計的實體方法
sum()
min()
max()
mean()

In [56]:
s.sum(axis=1)
np.sum(s,axis=1)

array([359, 297, 321, 400, 380, 364, 424, 342, 300, 390, 336, 373, 390,
       312, 387, 349, 412, 381, 368, 366, 379, 285, 318, 310, 366, 381,
       371, 331, 343, 396, 397, 373, 352, 349, 419, 395, 386, 371, 351,
       309, 388, 448, 376, 356, 371, 353, 407, 371, 358, 400])

In [53]:
s[:30].mean(axis=1)

array([71.8, 59.4, 64.2, 80. , 76. , 72.8, 84.8, 68.4, 60. , 78. , 67.2,
       74.6, 78. , 62.4, 77.4, 69.8, 82.4, 76.2, 73.6, 73.2, 75.8, 57. ,
       63.6, 62. , 73.2, 76.2, 74.2, 66.2, 68.6, 79.2])

In [54]:
s[:,0].max(axis=0)
s[:,0].min(axis=0)

np.int32(51)